/* sysdate */
select sysdate from dual;

/* round */
SELECT SYSDATE TODAY, ROUND(SYSDATE), ROUND(DATE '15-06-16','MM') ROUNDED_MONTH, ROUND(DATE '15-07-01','RR') ROUNDED_YEAR FROM DUAL;

/* trunc */
SELECT SYSDATE TODAY, TRUNC(SYSDATE), TRUNC(DATE '15-06-16','MM') ROUNDED_MONTH, TRUNC(DATE '15-07-01','RR') ROUNDED_YEAR FROM DUAL;

/* next day */
select next_day('04-JUN-15', 'Friday'), next_day('04-JUN-15', 'Sunday') from dual;
select next_day(to_date('04-JUN-15'), 'Friday') from dual;
select next_day('04-JUN-15', 'Friday') from dual;
select next_day(DATE '15-06-04', 'Friday') from dual;
select to_char(DATE '15-06-04', 'DD-MM-RRRR HH24:MI:SS'), to_char(to_date('04-JUN-15'), 'DD-MM-RRRR HH24:MI:SS') from dual;

/* last day */
SELECT LAST_DAY('14-FEB-11'), LAST_DAY('20-FEB-12') FROM DUAL;

/* add months */
SELECT ADD_MONTHS('31-JAN-11', 1), ADD_MONTHS('31-JAN-11',-2), ADD_MONTHS('01-NOV-11',4) FROM DUAL;

/* months_between */
SELECT MONTHS_BETWEEN('12-JUN-14','03-OCT-13') FROM DUAL;
SELECT MONTHS_BETWEEN('03-OCT-13', '12-JUN-14') FROM DUAL;
SELECT MONTHS_BETWEEN('06-JUN-15', '06-MAY-15'), MONTHS_BETWEEN('06-MAY-15', '06-JUN-15') FROM DUAL;

/* numtoyminterval */
SELECT NUMTOYMINTERVAL(27,'MONTH') FROM DUAL;
SELECT NUMTOYMINTERVAL(27, 'YEAR') FROM DUAL;

/* numtodsinterval */
SELECT NUMTODSINTERVAL(4.86, 'HOUR') from dual;
SELECT NUMTODSINTERVAL(36,'HOUR') FROM DUAL;
SELECT NUMTODSINTERVAL(36.353,'DAY') FROM DUAL;
SELECT NUMTODSINTERVAL(36.353,'HOUR') FROM DUAL;
SELECT NUMTODSINTERVAL(36.353,'MINUTE') FROM DUAL;
SELECT NUMTODSINTERVAL(36.353,'SECOND') FROM DUAL;